services:
  - type: web
    name: tomagochiweb-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tomagochiweb-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://tamagotchi-web.vercel.app

databases:
  - name: tomagochiweb-db
    databaseName: tomagochi
    plan: free
